### ISSUE TITLE
Uploading Dataset

### ISSUE THREAD

**Issue by shivam-bhardwaj-sb** [mk-gurucharan/Face-Mask-Detection#1]
How you had uploaded dataset? Or how can I upload dataset on google colab?

**Comment by RAVIKIRAN-DHULIPALA** [comment]
You can upload the dataset to colab using upload option. If your dataset is larger in size it may take hours to upload.

So my suggestion is to upload your dataset to any **cloud storage bucket** and make that dataset as **public link** and use it in colab.

I have done the same thing
